# Generated by Django 4.2.10 on 2024-02-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='town_city',
            field=models.CharField(default='Sausage', max_length=40),
            preserve_default=False,
        ),
    ]
