# Generated by Django 4.2.10 on 2024-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='UK', max_length=50),
        ),
    ]
