# Generated by Django 4.2.10 on 2024-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default=324, max_length=25),
            preserve_default=False,
        ),
    ]
