# Generated by Django 4.2.10 on 2024-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_ref',
            field=models.CharField(default='hsh337', editable=False, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
