# Generated by Django 4.2.10 on 2024-03-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_message_ref'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
