# Generated by Django 4.2.10 on 2024-03-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'get_latest_by': 'date_added'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='artists.artist'),
        ),
    ]
