# Generated by Django 4.2.10 on 2024-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'get_latest_by': 'artist'},
        ),
    ]
