# Generated by Django 4.2.10 on 2024-03-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_testimonial_options_alter_testimonial_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='status',
        ),
    ]
