# Generated by Django 4.2.10 on 2024-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_alter_testimonial_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='artist',
            field=models.CharField(default='sausage', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
