# Generated by Django 4.2.10 on 2024-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_testimonial_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='1995-08-12 20:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='artist',
            field=models.CharField(max_length=250),
        ),
    ]
