# Generated by Django 4.2.10 on 2024-03-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_alter_testimonial_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='artist',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='artists.artist'),
            preserve_default=False,
        ),
    ]
