# Generated by Django 4.2.10 on 2024-03-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='artist',
        ),
    ]
