# Generated by Django 4.2.10 on 2024-02-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-15 10:08'),
            preserve_default=False,
        ),
    ]
