# Generated by Django 4.2.10 on 2024-02-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='na', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
