# Generated by Django 4.2.10 on 2024-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_artist_slug_alter_artist_name_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
