# Generated by Django 4.2.10 on 2024-02-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
        migrations.AddField(
            model_name='artist',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
