# Generated by Django 4.2.10 on 2024-02-27 12:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
