# Generated by Django 4.2.10 on 2024-03-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_alter_testimonial_artist'),
        ('products', '0015_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
